### ISSUE TITLE
SPFx Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType')

### ISSUE THREAD

**Issue by JasonDCrandall** [OfficeDev/TeamsFx#10144]
**Describe the bug**
When building an SPFx Teams tab using the Teams Toolkit, I get this error whenever I try to load the application without the debug scripts: Error initializing application. Error: TypeError: Cannot read properties of undefined (reading 'componentType'). If I load the application with the debug scripts, the app loads fine, but this makes it impossible for me to publish it without it breaking.

**To Reproduce**
1. Open your SPFx app with the Microsoft Teams Toolkit in Visual Studio Code
2. Click on the 'Preview Your Teams App' button on the side panel 
3. If prompted, login to your org in the browser window that pops up
4. Add the app to teams when prompted
5. Click "Don't load debug scripts"

**Expected behavior**
Once clicked, the app will load and display the error

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/50968840/203a6fa5-0e14-4a9a-8ff5-b060abc1d131)
![image](https://github.com/OfficeDev/TeamsFx/assets/50968840/48d361fe-19b0-421c-ade1-649ac08a3a51)

**VS Code Extension Information (please complete the following information):**
 - OS: macOS
 - Version v5.2.0

**CLI Information (please complete the following information):**

**Additional context**

**Comment by HuihuiWu-Microsoft** [comment]
Hi @JasonDCrandall, thanks for reporting issue to us!

According to your description, you clicked 'Preview Your Teams App (F5)' tree item on tree view first. Then I believe you choose 'Teams workbench' configuration before the issue happens. Currently all configurations in launch.json are for local env. So it's a must to load debug scripts to preview your web part. So this is expected behavior in Teams Toolkit.

I don't quite understand what you mean 'If I load the application with the debug scripts, the app loads fine, but this makes it impossible for me to publish it without it breaking'. But if you would like to preview your app in remote env instead of local one, you can click 'Preview App' button on your selected env:
![image](https://github.com/OfficeDev/TeamsFx/assets/73154171/7749198d-e08e-4cdf-be94-c453e18c589d)

Besides the issue, I think this is a nice catch to let us know maybe we can improve to align the preview behavior to also include remote launch in launch.json. I'll create an item for that to track. Thanks again.

**Comment by BrucedeMink** [comment]
I am having the same issue listed above... Can someone assist me, please?
![LoadedBugScripts](https://github.com/OfficeDev/TeamsFx/assets/159413850/7b2b9b65-3db8-4683-b8ed-3f5d4ed64ccb)
![PublishedError](https://github.com/OfficeDev/TeamsFx/assets/159413850/cbc583ab-85e4-4156-a490-c73e502eb71a)
![TestPreview](https://github.com/OfficeDev/TeamsFx/assets/159413850/39dae5ed-8883-4201-a276-c910c7f96595)

**Comment by saldoc** [comment]
I'm also experiencing this issue. Is there any update on this?

**Comment by HuihuiWu-Microsoft** [comment]
Hi @BrucedeMink  and @saldoc, as I commented above, if you're using Teams workbench to do local debug, you have to select 'Load debug scripts' option so web part can be loaded successfully.

**Comment by BrucedeMink** [comment]
Thanks for you help Ms Wu!
