### ISSUE TITLE
Executing lifecycle deploy Fail on MacOs M1

### ISSUE THREAD

**Issue by pieropappalardo** [OfficeDev/TeamsFx#10966]
**Describe the bug**
during the deploy step of the lifecycle the botnet build failed.

.nuget/packages/microsoft.azure.webjobs.script.extensionsmetadatagenerator/1.1.3/build/Microsoft.Azure.WebJobs.Script.ExtensionsMetadataGenerator.targets(33,5): error : Metadata generation failed. Exit code: '130' Error: 'Failed to load /usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/libhostpolicy.dylib, error: dlopen(/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/libhostpolicy.dylib, 0x0001): tried: '/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')),
'/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18/libhostpolicy.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')) An error occurred while loading required library libhostpolicy.dylib from [/usr/local/share/dotnet/shared/Microsoft.NETCore.App/3.1.18]'  

**To Reproduce**
1. Download on VSCode Teams Toolkit
2. Create any project
3. debug on chrome (F5)

**Expected behavior**
should deploy
 
**VS Code Extension Information (please complete the following information):**
 - OS: Sonoma
 - Version 14.3.1

**CLI Information (please complete the following information):**
 - node: 18.18.2

**Comment by Siglud** [comment]
Please provide your Teams Toolkit version and the type of project you wish to create. 

Additionally, if you are experiencing an issue with Dotnet on Mac M1, please refer to (this link)[https://github.com/dotnet/sdk/issues/27761] for more information. 

If you would like to create a NodeJS project, use last preview or stable version greater than 5.5.0. All dependencies related to Dotnet have been removed from these versions.

**Comment by pieropappalardo** [comment]
Teams Toolkit version 5.4.1,
Basic Tab with React and Fluent UI,
question is I don't have problems with Dotnet on Mac. it's the toolkit looking for x64 instead of arm64

**Comment by Siglud** [comment]
I believe the root cause is that the Dotnet installer cannot recognize your system's version of Dotnet as a valid requirement. 

To avoid this issue, you can either remove the `dotnet: true` line from the `devTool/install` driver in your `teamsapp.local.yml` to disable the Dotnet installer, or install dotnet 6.0 on your system to prevent validation failure. 

Alternatively, you could wait for about a week until 5.6.0 stable version is released and create a new project of the same type; then you will find that the Dotnet requirement has disappeared.
