### ISSUE TITLE
Upload failed due to an invalid BotId in your manifest

### ISSUE THREAD

**Issue by pmcilreavy** [OfficeDev/TeamsFx#11146]
**Describe the bug**
Unable to test/deploy a new bot app due to "Upload failed due to an invalid BotId in your manifest".

**To Reproduce**
1. Create new C# teams echo bot in visual studio 2022 using the template
2. Follow the instructions and run the app
3. See error

**Expected behaviour**
I'm able to upload the app and then chat with it

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/3075792/e1ad1e73-cebd-4394-b286-fc5900f4a99c)

**Additional context**
- Visual Studio 2022, with latest bot templates and .net 8.0 etc.
- I am able to debug the app locally via the Bot Emulator.

**Comment by sarhaan7** [comment]
+ 1

i have a simple chatbot running, I had to redeploy the app and bot today for some reason and it no longer works after redeploying it.

- when i upload a manifest manually: The new teams client just fails with Uncaught (in promise) SyntaxError: "[object Object]" is not valid JSON and the old teams client returns Upload failed due to an invalid BotId in your manifest.
- The manifest is correctly validated by developer portal.
- it was working just fine as of 3pm EST on March 20th.
- test in web chat works fine
- if i click on 'Channels' in azure bot settings and click on 'Open in Teams' it does not work either

**Comment by nliu-ms** [comment]
Hey @pmcilreavy  @sarhaan7 , sorry for the inconvenience! This issue is possibly related to bot infra service, we can reproduce the error. We're trying to contact that team for more investigation.

Please check your network, let me know if you meet the same API failure/ error code:
![image](https://github.com/OfficeDev/TeamsFx/assets/71362691/49e3f6c3-9b75-4513-8a30-4a2fa4e593ab)
![image](https://github.com/OfficeDev/TeamsFx/assets/71362691/ff1e4be5-f4b4-4aab-8701-4e99680ed1cf)

**Comment by pmcilreavy** [comment]
@nliu-ms Yes confirmed.

![image](https://github.com/OfficeDev/TeamsFx/assets/3075792/fac74738-7800-4065-9191-3321a6027768)

**Comment by nliu-ms** [comment]
Hey @pmcilreavy  @sarhaan7, there was an outage from bot infra underneath, and it's recovered few hours ago. This issue should be mitigated. Please let me know if your apps can work now. 

If you're still meeting the same failure, can you please provide the detailed failure response of https://teams.microsoft.com/api/apps/part/msft/beta/users/apps/definitions/appPackage API? Especially the timestamp and X-serverrequestid header from error response. 

Thanks!

**Comment by pmcilreavy** [comment]
Yeah, seems good now.

**Comment by nliu-ms** [comment]
Thanks for the confirmation @pmcilreavy

**Comment by sarhaan7** [comment]
@nliu-ms it was working fine after the fix but im getting the same error again now :(

**Comment by sarhaan7** [comment]
I was able to run this on MS Teams web client however:

I'm trying Single Tenant SSO with `https://github.com/OfficeDev/Microsoft-Teams-Samples/tree/main/samples/bot-teams-authentication/nodejs`, SSO works in Web Chat but does not show anything in teams client. I'm assuming this isn't the right place for this issue so can you direct me to the appropriate people/repo? thank you!
