### ISSUE TITLE
Visual Studio Auth Output every second without using the Teams Tab

### ISSUE THREAD

**Issue by thomyg** [OfficeDev/TeamsFx#1246]
**Describe the bug**

Don't know if it's a bug, or just a minor glitch, but Visual Studio keeps writing debug output about authentication multiple times every second without actually a user doing something in/with the app.

**To Reproduce**

- Create new project with Teams template
- Configure SSO
- Press F5
- Not clicking on the "Authorize" button or anywhere else

**Expected behavior**

Auth configuration and setup not writing debug output in a while loop.

**Screenshots**

![TeamsToolkitOutput_Small](https://user-images.githubusercontent.com/10920072/120203619-32b2ef80-c228-11eb-99c8-494a05bddf1d.gif)

**Comment by JerryYangKai** [comment]
Hi @thomyg, I can not repro this issue, follow the steps and I got this output.
![image](https://user-images.githubusercontent.com/53805504/120256869-a94ffb80-c2c1-11eb-847e-820d3900562b.png)

Any more information would be helpful for me.

**Comment by thomyg** [comment]
hi @JerryYangKai!

Thx for looking into this.  

I'm opening VS, create a new project and click on the SSO config menu. After that just F5 and doing nothing in the app or anything else. 

Could this be related to me having multiple accounts connected in Visual Studio? 

Tried it again without changing the code and between the output above it seems that every few seconds this exception gets thrown:

![image](https://user-images.githubusercontent.com/10920072/120484915-d4b31300-c3b3-11eb-81b7-a7f265d93226.png)

Happy to jump on a call next week if this helps. I'm in the CET time zone, depending on where you are, but I'm sure we can find a 30 min slot.

**Comment by SLdragon** [comment]
Hi, @thomyg , I tried your steps, but cannot repro your issue.
From your logs, seems some code periodically try to get user info, for quick troubleshooting, you can add a break point in this place to check whether it  periodically been called:

![image](https://user-images.githubusercontent.com/5545529/120574280-9a984e80-c451-11eb-9b2c-dea55f0c497d.png)


By the way, I  tested the with this version: Microsoft.VisualStudio.TeamsToolkit.0.1.36.53175.vsix, if you use another version, please let me know, I will have a try

**Comment by SLdragon** [comment]
Hi, @thomyg ,
Your name comes before clicking Authorize button is expected, because your name is come from SSO token, and this can be obtained from Teams without login.

Authorize button is to get you graph access token, so it need your consent.

I think this issue may related to the template, some logic is not correct, so it periodically call the the "GetInfoAsync" function and you will see a lot of logs. It expects to only call once.

I will try your version to check whether I can reproduce it, thanks!

**Comment by SLdragon** [comment]
Hi, @thomyg ,
I tried your version and found the problem:

There is a function OnAfterRenderAsync:

![image](https://user-images.githubusercontent.com/5545529/121456527-cf1f8380-c9d8-11eb-82f4-bb90e58a19c0.png)
 
OnAfterRenderAsync will be called periodically because each time this function will trigger StateHasChanged.

So you can update the function like this to avoid this problem:

![image](https://user-images.githubusercontent.com/5545529/121457185-d7c48980-c9d9-11eb-9b91-1eb90290b0ce.png)


I will ask our teams members to fix this issue, thanks for you report!

**Comment by JerryYangKai** [comment]
Thanks @thomyg and @SLdragon , I will fix it in next release.

**Comment by JerryYangKai** [comment]
The new version of VS Teams Toolkit is availbale now in marketplace, we have fix the bug in this release, please upgrade and try it.
