### ISSUE TITLE
Different behavior in app provisioning

### ISSUE THREAD

**Issue by stas-linearb** [OfficeDev/TeamsFx#1402]
The toolkit creates successfully a new project. 
It provisioning the app(even we don't have any subscription) every time on "Start Debugging". Works perfectly.

On other hand, if I want to make "Provision in the Cloud" or "Deploy to the Cloud" using the menu of the toolkit, it always fails with the error:

[Solution.ProvisionFailure]: No Azure Subscription found for your account. Provision resources failed, subscription id: 'undefined', resource group: 'undefined'. You can choose to rollback to delete the resource group and redo provision.

It looks like inconsistent behavior.

I have Microsoft 365 subscription, **but I don't have** Azure Subscription.

Why it does not depend on Azure subscription on "Start Debugging" and depend on manual operations?

VS Code Version: 1.57.0 (Universal)
Teams toolkit version: v2.1.0
OS: MacOS Big Sur - Version 11.4

**Comment by MuyangAmigo** [comment]
Hello @stas-linearb, Thank you for bringing this to our attention and I'm sorry to hear that this confuses you. The `Provison` here in output of "Start Debugging" and "Provision in the Cloud" means slightly different things, please allow me to first explain a little bit in detail:
* In "Start Debugging", the tool is provisioning an app (an Azure Active Directory app) in your tenant, it only requires to know your Microsoft 365 subscription because there is no cloud resources needed and everything is running in your local machine.
* In "Provision in the Cloud", in addition to provision an app, it also refers to create resources in the cloud that will help host your app. For example, if you are develop a tab app, an Azure Storage resource will be created in this step so that you could deploy your app to this resource in next step with command "Deploy to the Cloud".

We will be more careful on the output messaging to make this clear.

**Comment by stas-linearb** [comment]
Thank you for clarifying the issue.

From your answer, I realize that the bot does not need any cloud resources? Is it correct?
That means, that for the production APP with a bot, I don't need any subscription? 
I'm asking you because in env.default.json I found variable declaration "skuName" with the value "F1", which means "Free and Shared" service plan. Every message that a bot receives passes through Azure servers, it makes sense for resources participating in the process and performance.

**Comment by MuyangAmigo** [comment]
Hey, I'm more curious about what you mean by "Production App" and what are you trying to achieve. 

I'm assuming you want the code to be deployed somewhere and having the bot up and running without any locally hosted services to support you production usage? 

If that's case, the Teams Toolkit can help in a way that we will create a resource in Azure for you to host your bot (behind the scene it's an App Service). This feature is handled by "Provision" (to create Azure Resource) and "Deploy" (To Deploy your code) command, and still an Azure subscription will be required. 

Aslo, as you mentioned, the App Service we provisioned is on the free tier.

**Comment by stas-linearb** [comment]
Hi,

The bot will be deployed to AWS.
As I understand, we don't need to create Azure subscription.

**Comment by MuyangAmigo** [comment]
@stas-linearb Thank you for explaining your scenario to us. Although we don't have built-in support to deploy your code to AWS, we are interested to consider this in our future roadmap. We will close this issue for now, feel free to open another one if you still have questions or meet another issue.
