### ISSUE TITLE
Error 403 When updating Description / JobTitle Field via MS Graph

### ISSUE THREAD

**Issue by grumpykiwi** [OfficeDev/TeamsFx#1796]
**Describe the bug**
I have a Teams FX app that I have written where I want the ability for the signed in user to be able to update specific non critical fields such as job title, office location and various phones

In order to make sure I can do this I tried this in Graph Explorer. I attempted to update job description to "Sales" but receive a 403 error. My MS Identity account is tied to AAD and has all the permissions to do this (user.readwrite etc).

**Expected behavior**
200 OK

**Screenshots**

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11 latest build
 - Visual Studio 2019 16.10.4
 - Teams Toolkit 0.1.50.37522

Background. Our on premises is currently running Active Directory with the AD 2000 schema and using active sync to replicate to AAD. My IT guy says 2 way sync is available with AD schema 2008 and above. They plan on migrating to Server 2016 or above but have some old DCs to upgrade at the same time. 

Is the 403 due to the age of our AD schema? Ie. Is the update being arbitrarily denied due to that, or is this a permissions issue with the app registration / delegated permissions, etc ?

How do I tell?

There may be a more appropriate place to ask this question, but the one place I know of, url below, dont seem to answer very questions very often.

[https://techcommunity.microsoft.com/t5/microsoft-365-developer-platform/idb-p/Microsoft365DeveloperPlatform/label-name/Microsoft Graph)

Thanks

**Comment by blackchoey** [comment]
Hi @grumpykiwi thanks for reaching us! Per my understanding, you're trying to update your user profile in Graph Explorer but failed with 403 response code. Please let me know if I have any misunderstanding.

I can provide some common check items for your situation:
1. Are you invoking the `https://graph.microsoft.com/v1.0/me` API? If not you may try this API (instead of `/users/{id}`) to see if it requires less privilege. 
2. Though the token used by Graph Explorer contains "User.ReadWrite" scope, it doesn't mean your account already has related permission to make desired changes. There're still additional permission checks during the API call. Many of the scopes may beyond our actual account permissions (e.g. Directory.ReadWrite.All). You can double check on this.

If the above tips cannot help, you may raise an issue for following document [Update user - Microsoft Graph v1.0 | Microsoft Docs](https://docs.microsoft.com/en-us/graph/api/user-update?view=graph-rest-1.0&tabs=http#response-3) at the end of the doc page to gain timely responses.

**Comment by grumpykiwi** [comment]
Thanks for the reply

I have tried invoking the update via the /me and the /users/{id} route. Same result.

I will try the whole process via Fiddler instead of Graph Explorer and see if that makes a difference. I have an app registration that has full r/w to user, directory, and group so that should not be an issue.

**Comment by grumpykiwi** [comment]
Same issue in Postman

`{
    "error": {
        "code": "Authorization_RequestDenied",
        "message": "Insufficient privileges to complete the operation.",
        "innerError": {
            "date": "2021-08-02T17:00:42",
            "request-id": "e2b23771-6eea-4a7d-855b-8686174a90b7",
            "client-request-id": "e2b23771-6eea-4a7d-855b-8686174a90b7"
        }
    }
}`

I guess I will wait until my IT guys can get their act together and upgrade our AD schema. Not holding my breath

**Comment by blackchoey** [comment]
Thank you @grumpykiwi for the update. Do you have further questions for us?

**Comment by grumpykiwi** [comment]
Thanks. No, I'm good at this stage. You can go ahead and close the ticket.


Mark Nash
Senior Software Engineer        [cid:PC_42x23_fbb4e57e-65d2-4c41-b09e-ffa9f4a3c468.png]

PartnerComm, Inc.
Winner of 76 IABC Gold Quills
2021 Large Agency of the Year
2304 W Interstate 20, Suite 250
Arlington, TX 76017
        [cid:pcomm25+_471933a4-f842-490b-84d4-910cf0397a29.png]

Office: (817) 465-9277
***@***.***
www.partnercomm.net<http://www.partnercomm.net>





This e-mail transmission may contain confidential information or may be otherwise legally privileged. If you are not the intended recipient you are hereby notified that any use, disclosure, copying, forwarding, or distribution of any of the information contained in or attached to this message is STRICTLY PROHIBITED.

________________________________

**Comment by blackchoey** [comment]
Thank you. Feel free to open new issues when you meet other problems during Teams app development.
