### ISSUE TITLE
material-ui breaking local debug

### ISSUE THREAD

**Issue by KristapsD** [OfficeDev/TeamsFx#2076]
**Describe the bug**
Using material-ui elements breaks local debug react.
error i recieve:  Invalid hook call. Hooks can only be called inside of the body of a function component.

**To Reproduce**
1. create new teams app project
2. npm install @material-ui/core in the root folder of the app
3. add any material UI component to tab.jsx
4. locally debug it

**Expected behavior**
renders the ui using material-ui elements

**Screenshots**
It's enough to test it with this:
![image](https://user-images.githubusercontent.com/49512575/131001383-ce1bd73a-e8c6-4daf-a45b-5372220b3b1b.png)

**VS Code Extension Information (please complete the following information):**
 - OS: win 10
 - Version 2.5.0

**CLI Information (please complete the following information):**

**Additional context**
i was able to repro this issue on 2 different computers.
This suddenly started happening today, no idea what triggered it.

**Comment by KristapsD** [comment]
https://github.com/KristapsD/MaterialUiBreaksReact @hund030  here's my repository

**Comment by hund030** [comment]
@KristapsD I get the error with your repository.
```
./src/components/Tab.jsx
Module not found: Can't resolve '@material-ui/core' in '<myPath>\MaterialUiBreaksReact\tabs\src\components'
```
Seems it's just because you install materialUI in the root folder, just re-install it in tabs folder then everything work fine.
I can't come out a scenario that you have to install dependencies in root folder. Give me more information if you do.
And I wonder if you have installed material UI core in your global environment so that you get different error?
