### ISSUE TITLE
Delegate all start commands to npm scripts defined by users

### ISSUE THREAD

**Issue by zhenyasav** [OfficeDev/TeamsFx#2170]
https://github.com/OfficeDev/TeamsFx/blob/7171991f445a437053afa27c29bf0a5b9014c002/packages/cli/src/cmds/preview/constants.ts#L59

This specific start command should be part of the bot's "dev" script like so:
```ts
// packages/cli/src/cmds/preview/constants.ts
export const botStartTsCommand = `npm run dev`;
```
`package.json` inside `bot`:
```json
{
  "scripts" : {
    "dev": "nodemon --exec node --signal SIGINT -r ts-node/register index.ts"
  },
  "devDependencies": {
     "nodemon": "...",
     "ts-node":"..."
  }
}
```
This makes it simple for me to refactor / adapt the bot to my needs should I decide to do something simple like pass more arguments (like --inspect) or change the location of my `index.ts` to `src/index.ts` for example... It's definitely something we'd want to be defined in the project under an npm script, and not hardcoded in the tooling.

**Comment by swatDong** [comment]
@zhenyasav - thanks for your suggestions!
Yes, we do have the idea to support user to customize the start command (this is also the prerequisites to support different frameworks/languages). And your idea is suitable for our CLI `teamsfx preview` command.

In addition, VSC may have different behaviors from CLI. Here are my thoughts.

#### CLI
Define `dev` command in `package.json` and our toolkit always calls `npm run dev` with additional environment variables.

User can customize the detailed script and make sure local service is strated correctly.

#### VSC Extension
Define `teamsfx: bot start` in `.vscode/tasks.json` with some parameters (entry file, port, ...), and our toolkit construct the `nodemon -exec ...` command from input parameters.

User can customize the parameters in `tasks.json` and make sure local service is started correctly.

Note that in VSC, all customizations should be in `tasks.json`, not `package.json`. Because VSC task/debugger requires more input than a single start command (E.g., if user changes the start command, he/she should also provide problem matcher). And this is the similar customization flow as other extension like Azure Function.

**Comment by swatDong** [comment]
Agreed that key point is make `package.json` the source of truth, so user can customize the command in single place, then work for both CLI and VSC.
- `package.json`: provide `dev` command.
- **CLI**: our toolkit always calls `npm run dev` to launch service locally.
- **VSC**: toolkit provide wrapper in `tasks.json` and `launch.json`, and the underlying command is still `npm run dev`. In addition, toolkit provide doc or automated detection to tell user how to change port/problem matcher/other parameters.

**Comment by swatDong** [comment]
Closing this.

The Teams Toolkit v3.4 starts to support npm scripts (npm run dev:teamsfx) as start commands.
See [Manual Customizations](https://dev.to/azure/debugging-teams-app-locally-with-teams-toolkit-2b67#manual-customizations) as well.
