### ISSUE TITLE
VSCode Teams Toolkit extension won't load for a newly created project

### ISSUE THREAD

**Issue by arsdragonfly** [OfficeDev/TeamsFx#2594]
**Describe the bug**
VSCode Teams Toolkit extension won't load for a newly created project

**To Reproduce**
1. open a VSCode WSL window
2. create a new teams app with teams toolkit
3. launch Debug (Edge)
4. an error "command `fx-extension.validate-dependencies` not found" appears

**Expected behavior**
A debug window would launch.

**Screenshots**
![image](https://user-images.githubusercontent.com/4067473/137082029-4cc4c28f-9f72-4cae-b4c2-14d85450cb3f.png)

**VS Code Extension Information (please complete the following information):**
 - OS: WSL on Windows 11
 - Version v2.7.0 (preview)

**Comment by kuojianlu** [comment]
@arsdragonfly Sometimes the toolkit may be not well activated. I suppose reloading VSCode window may solve this issue.
1. In this project, select and run `Developer: Reload Window` from command palette
2. Wait for a while util the toolkit is well activated
3. Launch Debug (Edge)

**Comment by jayzhang** [comment]
@arsdragonfly: 
For short term, please follow what @kuojianlu said, don't trigger F5 before extension activated. 
For long term, @1openwindow , can you follow this issue by optimize the activation time for extension?

**Comment by 1openwindow** [comment]
@kuojianlu, @jayzhang , I think the root cause is not the activation time. The end users still can press F5 before teams toolkit activated. 
The right solution is monitor the onCommand trigger point. Please check this: https://github.com/OfficeDev/TeamsFx/blob/6835acba1cae9b1a83515019b309fbce148e218d/packages/vscode-extension/package.json#L62
