### ISSUE TITLE
bug(simpleauth): Library is using Newtonsoft.Json which is not included in project files

### ISSUE THREAD

**Issue by vnbaaij** [OfficeDev/TeamsFx#3097]
**Describe the bug**
As the tilte says, the library is using `Newtonsoft.Json` in a couple of places (https://github.com/OfficeDev/TeamsFx/blob/dev/packages/simpleauth/src/TeamsFxSimpleAuth/Components/Auth/AadAuthorizationHandler.cs#L45, https://github.com/OfficeDev/TeamsFx/blob/dev/packages/simpleauth/src/TeamsFxSimpleAuth/Components/Auth/AuthHandler.cs#L85 and others) but Newtonsoft.Json is not included as a `<PackageReference>` in the project files (SimpleAuth and SimpleAuth.Tests)

This leads to runtime errors when the library is used in a project that does not reference `Newtonsoft.Json` itself (like in a .NET 6 project that uses `System.Text.Json`)

**To Reproduce**
Look at the source line references above and check the `.csproj` files

**To resolve**
As Newtonsoft.Json is only being used to do simple serialization/deserialization, this can easily be replaced with standard `System.Text.Json` and `System.Text.Json.Serialization`. These changes port to  .NET 6 without modification.
A PR for making the necessary changes will be submitted.

**Comment by blackchoey** [comment]
Thank you @vnbaaij In our previous test, we found sometimes we will meet reference loop issue when ASP.NET Core serialize the exception during error handling. Since `System.Text.Json.Serialization` on ASP.NET Core 3.1 cannot handle reference loop, we uses newtonsoft.json as serializer. 
How do you think we add newtonsoft.json to `<PackageReference>` instead of switching to `System.Text.Json.Serialization` to fix this issue? Otherwise our customer may meet unexpected error caused by reference loop.

**Comment by vnbaaij** [comment]
If switching to `System.Text.Json` is not an option for now, `Newtonsoft.Json` should be included as a `<PackageReference>`

I'm not quite sure yet why this project would still need to be on .NET Core 3.1. Updating to a later version would bring benefits on speed, security and other areas (like switching to more modern `System.Text.Json`)

**Comment by blackchoey** [comment]
@vnbaaij Agree that upgrading to .NET 6 brings many benefits. Since .NET 6 is just released recently and we need sometime to figure out a good plan (e.g. consider users who only have .NET Core 3.1 installed), this might not happen very soon.
We will prepare a fix to add `Newtonsoft.Json` to `<PackageReference>`, and this is expected to release around mid December.

**Comment by blackchoey** [comment]
hi @vnbaaij the new package has already released. Please try the new package.

**Comment by blackchoey** [comment]
@vnbaaij  I'm closing this issue since it's fixed and we haven't heard from you for some time. Feel free to comment in the future and we will re-investigate.
