### ISSUE TITLE
Failed to read your profile. Please try again later

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/TeamsFx#3366]
**Describe the bug**
When running the Hello World Tab with Back End example I will constantly receive the following error
```
Failed to read your profile. Please try again later.
Details: ErrorWithCode.InternalError: Failed to get access token with error: Request failed with status code 401
```

**To Reproduce**
1. On the "Hello World Tab with back end example" in VSCode using the Teams Toolkit
2. Start debugging
3. Teams will open, install the app
4. Launch the app and click "Authorize" 

**Expected behavior**
The user profile photo should appear

**Screenshots**
![Animation (15)](https://user-images.githubusercontent.com/12785492/146197992-5142cb50-ad74-439b-9915-3a7c6c791be0.gif)

**VS Code Extension Information (please complete the following information):**
 - OS: Windows 11

**Additional context**
I have gotten the profile image to show in the past, it seems it sometimes works and sometimes doesn't. the sample apps provided in the tool kit often do not work.

**Comment by SLdragon** [comment]
Hi, @AnthonyPhan , I tried your steps, it works fine now.
From you images, seems the response auth code is corrupt so that you got 401 error, today the M365 login is not very stable, maybe this is the reason why the auth code is not valid.

If you still meet this error, you can add a break point in `useGraph.ts` file to get the detailed error messages when it throw error. we can take a look to find out what's wrong with it, thank you!

![image](https://user-images.githubusercontent.com/5545529/146325151-86a85d97-ef91-45b7-be6e-c28cd3e15785.png)

**Comment by AnthonyPhan** [comment]
Hi @SLdragon , It does look like the issue has automagically disappeared today. Perhaps it was due to M364 Auth stability on the 2 days that I was testing.

**Comment by SLdragon** [comment]
@AnthonyPhan , thank you for your feedback~
