### ISSUE TITLE
Cannot build package without M365 account

### ISSUE THREAD

**Issue by creage** [OfficeDev/TeamsFx#3753]
**Describe the bug**
After upgrading the `teamsfx-cli` from **0.9.1** to **0.10.1** I cannot execute the `teamsfx package --env prod` anymore, as the new CLI requires me to logon to my M365 account. This breaks my CI/CD.

**CLI Information (please complete the following information):**
 - OS: Windows 10
 - Version 0.10.1

**Comment by MuyangAmigo** [comment]
Hey, @creage Thank you for reporting this issue to us! This change is caused by grouping `validate manifest schema` and `package app manifest` operations together and executing validate command currently requires your M365 command.

Our team will look at this for further discussions and try to:
* Ungroup `package` and `validate` operation in `teamsfx package` command.
* Remove M365 account requirements in `validate` command.

In the meantime, you can use your previous CLI version as a temporary workaround.

**Comment by nliu-ms** [comment]
Hey @creage , we have released 0.11.0 version, which does not require M365 account to validate/build. Please try this out! Thanks!

teamsfx manifest validate

https://www.npmjs.com/package/@microsoft/teamsfx-cli/v/0.11.0

**Comment by LeHailender** [comment]
Can confirm, building without a M365 account works with version 0.11.0. thanks
