### ISSUE TITLE
Issue with TeamsFx in Microsoft Teams App project template running on .NET 6

### ISSUE THREAD

**Issue by robertstewartnz** [OfficeDev/TeamsFx#3756]
After creating a generic Microsoft Team App project in Visual Studio 2019, I opened it in VS 2022 and upgraded the runtime to .NET 6 to take advantage of updates to Razor in .NET 6.

However when calling this method in Microsoft.TeamFx.dll:

public override ValueTask<AccessToken> GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken);

as

await teamsUserCredential.GetTokenAsync(new TokenRequestContext(new string[] { _scope }), new System.Threading.CancellationToken());
 
I get this error

System.NotSupportedException: Serialization and deserialization of 'System.IntPtr' instances are not supported. Path: $.WaitHandle.Handle.

Check out this issue as it could provide some insight into the problem:

https://github.com/dotnet/runtime/issues/61648

**Comment by JerryYangKai** [comment]
Hi @robertstewartnz, thanks for your feedback.
This is caused by the version of our TeamsFx SDK, you could find it in the dependency.
<PackageReference Include="Microsoft.TeamsFx" Version="0.3.0-rc" />

Maybe you are using the version 0.1.0, this is for .Net 5. The upgraded version such as 0.3.0 I presented is for .Net 6, also there are some interface changes in 0.3.0.

A quick way for fix this is you can download the Preview version of VS 2022 (17.1 Preview4), that will deliver more features for .Net6 include hot reload. Our Teams Toolkit for VS 2022 is in Visual Studio installer, under ASP.NET and web development called Microsoft Teams development tools, you need to choose it.

**Comment by robertstewartnz** [comment]
Thanks Jerry. All sorted.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by adashen** [comment]
Close as the issue is solved.
