### ISSUE TITLE
Use 0.10.0 Azure account extension cannot get token for SqlServer

### ISSUE THREAD

**Issue by xiaolang124** [OfficeDev/TeamsFx#3971]
**To Reproduce**
1. Sign out account from Azure account extension and install/update 0.10.0 Azure account extension.
2. Create a teams project with sql, and provison. Provision will fail with error ```[Error] - code:SQL.DatabaseUserCreateError, message: Failed to create user 'helly02161deve6a89d' in database (helly02161deve6a89d), Could not retrieve the token associated with Visual Studio Code. Did you connect using the 'Azure Account' extension? You can follow https://aka.ms/teamsfx-sql-help to handle it.```
3. In the end I cannot provision successfully.

**Comment by xiaolang124** [comment]
Work around:
1. Downgrade Azure account extension to 0.9.11 and close auto update.
2. Sign in azure account and provision.

**Comment by xzf0587** [comment]
In addition, there could be SQL.DatabaseUserCreateError error when provisioning if you try to switch your Azure account in teams toolkit. It also be caused by Azure acount extension.

**Comment by xiaolang124** [comment]
Related issue: https://github.com/microsoft/vscode-azure-account/issues/451

**Comment by xzf0587** [comment]
Since the teams toolkit for VS Code has upgraded to 5.0. It will not use the token to add user to SQL server.  This error will not occur in 5.0 anymore.
If there is still such a need, please refer to [Integrate-Azure-SQL-Database](https://github.com/OfficeDev/TeamsFx/wiki/Integrate-Azure-SQL-Database-with-your-Teams-app )
