### ISSUE TITLE
Nix Support

### ISSUE THREAD

**Issue by AnthonyPhan** [OfficeDev/TeamsFx#4048]
**Is your feature request related to a problem? Please describe.**
Currently in our organisation we do no install packages like Node.js globally but rather define it as a dependency on the directory level using Nix. This works great however when trying to develop Teams app using TeamsFx and starting a debug session the TeamsFx plug runs prerequisite checks outside of the nix shell which contains all the dependencies associated with the project (e.g. nodejs and npm). 

**Describe the solution you'd like**
When running the debug, it should do all the prerequisite checks using the the default shell and within the scope of the current directly. 

**Additional context**
When I navigate the the hello world example Direnv loads node.js and npm into the shell and these are avilable but when i click the debug button it complains that :
`NPM Install for tab app (react-based)
   Failed to npm install for frontend`

**Comment by meifans** [comment]
@AnthonyPhan Thanks for your advice.
There are two problems:
1. Use your shell when you localdebug.
2. Skip Node Check.

For the first problem, you can set **automation profile** by following the steps below, so that Teamsfx can use the shell you specified when debugging.
1. Open VSCode 
3. Open Settings
4. Click **Edit in settings.json** 
![image](https://user-images.githubusercontent.com/12523371/156288626-a8f97d3a-70a3-4a6d-92fe-4c5cd829842d.png)
5.  Set **terminal.integrated.shell.windows** to the shell you want
![image](https://user-images.githubusercontent.com/12523371/156288939-37481a14-a39d-44bb-be87-2c66ab1042cb.png)


For the second problem, you can disable the Node Check by following the steps below:
1. Open VSCode 
2. Open Settings
3. Type **Prerequisite Check**
4. Set Node Check to false.
![image](https://user-images.githubusercontent.com/12523371/156290737-45c61ac6-9566-4300-925e-4fd7b30c909e.png)

Let me know if you have any questions :)
