### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by dash4397** [OfficeDev/TeamsFx#4141]
**Describe the bug**
I get this code anytime i try to run a code on my vscode 

sreenshot 

![image](https://user-images.githubusercontent.com/74638106/156940167-9820d25d-1931-4b71-9d64-77e57b5a92d6.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by kuojianlu** [comment]
@dash4397 Could you please share the steps to reproduce the behavior? 

From the screenshot above, I guess this error happens when you are running **Debug (Edge)**. Could you please run **Debug (Chrome)** (as shown below) to see if it can solve this error and unblock you to debug the project?
![image](https://user-images.githubusercontent.com/37978464/157228720-35a01aec-522c-4f1a-ae73-fdb5db7579f6.png)
