### ISSUE TITLE
Unit Testing in TeamsFx App

### ISSUE THREAD

**Issue by v-ashrirao** [OfficeDev/TeamsFx#4771]
We have built an app using TeamxFx. 
When we tried to write unit tests using JEST we are getting errors. 
Do we have some sample projects to refer to for this?
Is there any way to mock the context objects in TeamsFx App?

**Comment by eriolchan** [comment]
Thanks for sharing your feedback. Since current Teams App project is a JS/TS project, you can use any unit test framework for JS/TS, e.g. Mocha/JEST. If you need some sample, you can refer to TeamsFx repository for it.

Here is an example of [test case](https://github.com/OfficeDev/TeamsFx/blob/dev/packages/fx-core/tests/plugins/resource/frontend/unit/index.test.ts), in our practice, we use [Sinon](https://sinonjs.org/) for mocks.

**Comment by v-ashrirao** [comment]
@eriolchan, Thank you for your response but I am still getting error in setup itself.

![image](https://user-images.githubusercontent.com/100257227/167078270-86f9f84f-0d18-4f09-b5b9-5b7cf5d0380b.png)

Can you please let me know if I am missing any configuration?

**Comment by eriolchan** [comment]
It depends on what does your package.json file look like. This is a tutorial about setting up unit test for Node project, maybe you can get started from this. https://medium.com/serverlessguru/how-to-unit-test-with-nodejs-76967019ba56
