### ISSUE TITLE
Allow the Teamsfx CLI validate command to fail CI/CD

### ISSUE THREAD

**Issue by AndrewCraswell** [OfficeDev/TeamsFx#4844]
**Is your feature request related to a problem? Please describe.**
The `teamsfx validate` command allows validation of an environment's manifest and config files. But when the command fails, it doesn't appear to exit with a non-zero code in order to fail builds.

**Describe the solution you'd like**
Either throw an exception in such a way as to fail Azure Devops builds, or add a `throwOnError` argument of some kind so that exceptions can be opted into.

**Additional context**

This is the powershell script I'm using in my build pipeline:

``` powershell
$teamsfx = './node_modules/@microsoft/teamsfx-cli/cli.js'
$environments = (node $teamsfx env list --interactive false)

Write-Host "Building Teams manifests..."

ForEach ($env in $environments) {
  Write-Host ""
  Write-Host "Processing $($env.ToUpper())..."
  node $teamsfx validate --env $env --interactive false
  node $teamsfx package --env $env --interactive false
}
```
Executing the script in the pipeline will show the correct error text when the manifests are not valid, but it does not break the build. I tried a number of ways to get access to the result text and check the error code and throw my own exception, but I couldn't get Powershell to be able to pipe the output from the CLI to evaluate.

![image](https://user-images.githubusercontent.com/1908292/165172396-dad13405-669d-404d-89e8-6c86cfdeb2d7.png)

**Comment by nliu-ms** [comment]
Thanks @AndrewCraswell , I will put it into backlog and talk about it with pm. Will get back to you if there is an update. Thanks!

**Comment by MuyangAmigo** [comment]
Hey @AndrewCraswell, in your case are you expecting TeamsFx to not build the packages if the `teamsfx validate` command fails?

**Comment by AndrewCraswell** [comment]
My expectation would be that the `validate` command would exit with a non-zero code so that it breaks CI if used within a pipeline

**Comment by MuyangAmigo** [comment]
Thanks for the input, our team will work on this and update you. Please stay tuned!

**Comment by nliu-ms** [comment]
Hey @AndrewCraswell , with some investigations, I think the problem may come from Azure Devops pipeline. The cli does return non-zero exit code, but the pipeline can ignore the error and continue.

Please check the following two settings:
1) Do not set continueOnError to be true 
![image](https://user-images.githubusercontent.com/71362691/169769766-b205219e-a5a2-4dcf-8c85-ff86d559d411.png)

2) set -e for bash script to immediately fail the pipe
![image](https://user-images.githubusercontent.com/71362691/169771706-5fa7480d-a846-4ce0-9466-048b7f2f78a4.png)
reference: https://unix.stackexchange.com/questions/597500/what-is-the-meaning-of-set-e-o-pipefail

Please let me know if it works for you, thanks!

**Comment by AndrewCraswell** [comment]
Would you mind sharing the script you're using to validate that it is breaking builds? The Powershell I posted above is not failing our build, so I'm hoping to find the differences between our scripts and use it as a baseline to understand what I'm doing wrong.

**Comment by IvanJobs** [comment]
@AndrewCraswell Hi Andrew, to share the script you mentioned previously, check the yml files under https://github.com/OfficeDev/TeamsFx/tree/dev/packages/fx-core/templates/plugins/resource/cicd/azdo
BTW, if you want to set up your CI/CD Pipelines on Azure DevOps for your Teams App Projects, I recommend you try our latest CI/CD support inside Teams Toolkit / TeamsFx CLI as you can infer how to use them by the following GIFs: 
![gifgit](https://user-images.githubusercontent.com/1803943/170912777-c83e013e-4339-4aaf-abe1-a0e3c4e5e283.gif)
![gifgit (1)](https://user-images.githubusercontent.com/1803943/170912788-17096f0f-c284-4623-b98a-4c748cc15a38.gif)

Since you're using PowerShell scripts in CI/CD and the scripts we provided were based on Bash, I believe they might not be a good reference for you. To fail on non-zero return code in PowerShell, I believe the following would help solve your issue directly which was extracted from https://stackoverflow.com/questions/47032005/why-does-a-powershell-script-not-end-when-there-is-a-non-zero-exit-code-using-th:
![image](https://user-images.githubusercontent.com/1803943/170913207-6ca9ce2a-2d13-40ce-85e1-526bb67f49a0.png)

Any feedbacks to tell us your current status would be appreciated, thanks.

**Comment by AndrewCraswell** [comment]
Ah this is awesome. Actually, I think using the bash script is even better. This helped a lot:
https://github.com/OfficeDev/TeamsFx/blob/dev/packages/fx-core/templates/plugins/resource/cicd/azdo/publish.yml

Thanks for setting me straight. Closing as resolved :)
