### ISSUE TITLE
[Project template][Visual Studio] Unable to create project with dot in name

### ISSUE THREAD

**Issue by xperiandri** [OfficeDev/TeamsFx#5107]
**Describe the bug**
If you try to create an app with a dot in the name the project creation wizard will throw an exception

**To Reproduce**
1. Open Visual Studio 17.2
2. Create a new project with the name `TDL.Teams`
3. See 
![image](https://user-images.githubusercontent.com/2365592/169621108-b861f602-d4f2-4f12-b5d9-140488982d4a.png)

**Expected behavior**
Project creates successfully

**VS Information:**
 - OS: Windows 11 Pro Ukr 10.0.22000.675
 - VSIX Version 0.2.46.31853

**Comment by Alive-Fish** [comment]
@xperiandri Thanks for your feedback. Currently the project name `TDL.Teams` is illegal in our toolkit because it contains the `.` character. The project name pattern should be `^[a-zA-Z][\\da-zA-Z]+$`.

I'm sorry the error message is not readable. I will investigate it more and make it better. Thank you.

**Comment by xperiandri** [comment]
Fixed
