### ISSUE TITLE
Teams proactive notifications not working

### ISSUE THREAD

**Issue by arielpriya** [OfficeDev/TeamsFx#5633]
I am not getting any proactive notification to my teams bot.

After using attached references for proactive message I tried to send proactive message using bot framework emulator and added localhost url, MicrosoftAppId and MicrosoftAppPassword in emulator also added the MicrosoftAppId and MicrosoftAppPassword to proactive code, when I started process to test this app on emulator I am getting unauthorize error. Now I'll try to host it on any web server to check this issue.

I have followed these references : - https://github.com/MicrosoftDocs/msteams-docs/blob/master/msteams-platform/assets/downloads/SendProactiveMessages.zip - https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-send-proactive?tutorial-step=3

**Comment by zyxiaoyuer** [comment]
Hi @arielpriya, thanks for reaching out! Glad to see that you are interested in building proactive message apps. But I would not suggest you to follow that tutorials because that one is a little bit out-of-dated. Could you please follow [this tutorial ](https://docs.microsoft.com/en-us/microsoftteams/platform/sbs-gs-notificationbot?tabs=vscode) to build a notification bot using Teams toolkit, give it a try and then we can see if you have any other issues.
