### ISSUE TITLE
Handling Error in Teams when there is no SharePoint app uploaded in app catalogue

### ISSUE THREAD

**Issue by JarialAnkur** [OfficeDev/TeamsFx#5753]
I am having a SharePoint solution that is uploaded to the tenant app catalog. For the same SharePoint solution, I have the TeamsPackage .zip file which can be uploaded to Microsoft Teams and the app will load successfully.
But if I am not having my SharePoint Solution app uploaded to the tenant app catalog, and I try to upload the TeamsPackage .zip file to Microsoft Teams then I get a 404 error and there is no way for me to do error handling and present a custom message to the end user. 
I am not using any client secrets or application Ids.

Note:- This is for a static personal app only.

1. Create a hello world SPFx teams solution
2. After compiling it you will get the SharePoint package (.sppkg) and teamspackage .zip file.
3. Go To Microsoft Teams and upload a custom app, select the teamspackage .zip file and then add it.

**Expected behavior**
As below in the screenshot, we get a default error by Microsoft teams, but here I need to give my own custom message to the user.

**Screenshots**
![error](https://user-images.githubusercontent.com/49793242/183751876-d3336c94-9139-42f3-b12f-c8b3ef1a2e52.jpg)

**Comment by HuihuiWu-Microsoft** [comment]
Hi @JarialAnkur , I think this is expected behavior.  If you don't upload and deploy the solution in SharePoint app catalog, then the tab url specified in Teams App manifest doesn't exist which causes an error(See more details at https://docs.microsoft.com/en-us/sharepoint/dev/spfx/build-for-teams-configure-in-teams#personal-app-configuration-ui-web-part). 
As you mentioned in 'Expected behavior' section, you want to give your own custom message to the user. I'd like to know more about your idea on better handling error in Teams to improve our product if possible.

**Comment by JarialAnkur** [comment]
Can't we add a simple HTML page in the TeamsPackage.zip file, which will eventually run and query for the SharePoint App in the app catalog? 
If it doesn't exist, we can show a custom error message, including the link to the SharePoint store where the desired app is uploaded.
and
If the app is present in the app catalog, then it should simply go by the content Url or the tab URL specified in the manifest file.

**Comment by HuihuiWu-Microsoft** [comment]
> Thank You @HuihuiWu-Microsoft for your kind response
> 
> Can't we add a simple HTML page in the TeamsPackage.zip file, which will eventually run and query for the SharePoint App in the app catalog? If it doesn't exist, we can show a custom error message, including the link to the SharePoint store where the desired app is uploaded. and If the app is present in the app catalog, then it should simply go by the content Url or the tab URL specified in the manifest file.

Hi @JarialAnkur , the TeamsPackage.zip file is a standard zip file which is defined to have two icons and one manifest file(https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/deploy-and-publish/apps-publish-overview#create-your-app-package). So additional pages in the zip file won't work to integrate with Teams. The only way I can think of is to replace existing contentUrl with the customized url you mentioned(In  the customized url, check whether the app exists or not and show related error).  But we'll have to embed the SPFx webpart page into this page. We prefer to keep existing SPFx experience as it is at least for now since this should be no big problem for users if he follow the steps in our Toolkit. 
Still thank you for the suggestion, maybe we'll look into this if more users are having the issue.
