### ISSUE TITLE
getToken method fails on Teams mobile application

### ISSUE THREAD

**Issue by facundoctes** [OfficeDev/TeamsFx#7532]
**Describe the bug**
We have an issue while trying to get the token after the login for a team's extension in the Teams app for mobile. 
After entering the user credentials in the login popup, the getToken method fails and returns an UiRequiredError. This issue is not happening on the web or in the desktop Teams application where we are able to get the token successfully.

The application is deployed in an Azure storage static website, and the package to install the application in Teams and the app registration was configured using an Azure CDN endpoint.

```
export const login = async (scopes: string[]) => {
  const teamsFx = new TeamsFx();
  await teamsFx.login(scopes);
  const credential = teamsFx.getCredential();
  const token = await credential.getToken(scopes);
  return token;
};
```

**Teams mobile app**
 - OS: iOS 16.1.1
 - Microsoft Teams: 4.22.1

**CLI Information:**
 - OS: Windows 10
 - @microsoft/teams-js: 2.2.0
 - @microsoft/teamsfx: 2.0.0

**Comment by KennethBWSong** [comment]
Hi @facundoctes Thank you for using our Toolkit. We are using [msal-browser](https://www.npmjs.com/package/%40azure/msal-browser) for authentication, and one potential reason of your problem is that msal cache in your auth pages is not correctly set to your session storage. To better trouble shoot, would you please provide:
1. Your auth-start.html and auth-end.html
2. Version of your `msal-browser`. You can check it in `package-lock.json`.

**Comment by facundoctes** [comment]
Thanks @KennethBWSong, I have installed msal-browser v 2.25.0 and worked.

**Comment by jkerst** [comment]
@facundoctes: We face a similar problem. Did you also update your auth-start and auth-end files?
