### ISSUE TITLE
"Something Went Wrong" When trying to launch Microsoft Teams App template

### ISSUE THREAD

**Issue by Aurimas-TheDev** [OfficeDev/TeamsFx#7608]
**Describe the bug**
When trying to launch Microsoft Teams App template from Visual Studio it throws an error of "Something Went Wrong". I just started to work on it today, made a fresh Azure Development account. Using Visual Studio 17.4.4.

**To Reproduce**
1. Go to Visual Studio
2. Click on "Create a new project"
3. Scroll down to Microsoft Teams App
4. Download and install ngrok (https://ngrok.com/)
5. Open a command prompt and run "ngrok http 5130"
6. Right-click your project and select Teams Toolkit > Prepare Teams App Dependencies. 
7. If prompted, sign in with a Microsoft 365 account for the Teams organization you want 
to install the app to.
8. Wait for it to load.
9. Press F5, or select the Debug > Start Debugging menu in Visual Studio
10. In the launched browser, select the Add button to load the app in Teams
11. See error

**Expected behavior**
Based on video: https://www.youtube.com/watch?v=n2HrdzpBg-8 it had to be added to Teams so I could use it to trigger bot. However it failed to add. I am still able to find it under search apps: 
![image](https://user-images.githubusercontent.com/10827948/215579174-18cd0209-7b68-4e09-8ede-8fd1a41dcaaf.png)
However, app still doesn't work:
![image](https://user-images.githubusercontent.com/10827948/215579347-269bb0ff-9287-45fa-9a62-5ee63e19dfce.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/10827948/215578365-20638c35-a59f-4e88-9cdf-dcc28770dafb.png)
![image](https://user-images.githubusercontent.com/10827948/215578428-51da337e-bfb5-4f1c-8f9e-4ac818cb8ad2.png)

**Operating System:**
 - OS: Windows 11 Pro
 - Version [e.g. 22]: 10.0.22621

**Comment by llowevad** [comment]
I ran into this issue today and noticed that in botframework.com, my bot had the Teams Channel added, but wasn't showing any health (such as "healthy").. took a look at the developer portal and checked the bot and noticed that "Teams" channel wasn't checked.. i checked to add it and the bot started working and botframework.com showed the health as "Healthy".

Developer Portal > Tools > Bot Management > select your bot > channels:
![image](https://user-images.githubusercontent.com/8823690/216113419-6e9ad2a9-6521-4a73-8929-a355b43c31fc.png)

**Comment by Aurimas-TheDev** [comment]
Thanks for your response. This was marked, so I guess it was not related with that. However, for some kind of unknonw reasons it started to work today... Not sure if I should close this pull request, or if you would like to continue investigation.

**Comment by nliu-ms** [comment]
Thanks @llowevad  for providing some insights. 

@Aurimas-TheDev  Did you log the console/Network info when you meet "Something went wrong" error? I may need more information to do the investigation, thanks!

**Comment by nliu-ms** [comment]
cc @IvanJobs  as it seems to be related to bot projects.

**Comment by andrewd666** [comment]
@Aurimas-TheDev  I had same issue now from a new Teams app project. I used @llowevad suggestion after I hit the "Something went wrong" when debugging the project through Ngrok, but my menu's different - Teams dev portal -> Tools -> Bot management -> Select the new bot -> Channels and then tick Microsoft Teams.  And its working now

**Comment by Aurimas-TheDev** [comment]
The thing is that I tried these steps, but it was marked already... next day it all worked anyway

**Comment by kuojianlu** [comment]
@llowevad Can you share which version of Teams Toolkit you used when encountering teams channel not completely added issue?

**Comment by llowevad** [comment]
Teams Toolkit version 4.2.1
VSCode Version 1.74.3

**Comment by nliu-ms** [comment]
Hi all, with some investigations the root cause does from **invalid/missing Teams channel configured in bot** caused by some underlying service live incident. We have reported the issue to the corresponding team and wait for their reply.

The workaround is basically the same as @llowevad described above:
1) Go to [Teams Developer Portal](https://dev.teams.microsoft.com/bots)
2) Find your bot
3) Check the Microsoft Teams channel and save
![image](https://user-images.githubusercontent.com/71362691/217416481-d52474da-0e5d-4e01-a032-3ef345bcd7ff.png)

Sorry for the inconvenience, I will keep updating the status in this issue.

**Comment by SLdragon** [comment]
By the way, if you meet the error `Upload failed due to an invalid botId in your manifest` as below: 
![image](https://user-images.githubusercontent.com/5545529/219288057-859c2420-ee95-435e-930e-f5cbfd69237b.png)

And cannot find the Bot directly from [Teams Developer Portal](https://dev.teams.microsoft.com/bots) bot page, you can follow the steps to fix this issue:

- Go to this URL: https://dev.teams.microsoft.com/bots/{YOUR_BOT_ID}/channels
- Enable Teams Channel as below: 
 
![image](https://user-images.githubusercontent.com/5545529/219288403-1ee9025c-caae-48ec-8470-3273cc60e0d6.png)

- Re-install your app, then it will works fine

**Comment by nliu-ms** [comment]
This issue has been mitigated from server side, the root cause is from some cache strategy. Thank you so much for all your patience! Please let me know if you still meet this error.

**Comment by christophemacabiau** [comment]
Hi @nliu-ms,

I have this error... "Upload failed due to an invalid BotId in your manifest."
The App manifest is successfully validated in developer portal.

Is this problem back?
