### ISSUE TITLE
TeamsFx 5 migration removes language-specific manifest

### ISSUE THREAD

**Issue by ThomasPe** [OfficeDev/TeamsFx#8732]
**Describe the bug**
I added an additional language-specific manifest file "manifest.de-DE.json" and linked to it in the main manifest.
After upgrading to the latest TeamsFx version the file was removed, causing the app not to start with a "missing file" error.

**Expected behavior**
Upgrade should preserve the language-specific manifest files.

**Screenshots**
<img width="410" alt="image" src="https://github.com/OfficeDev/TeamsFx/assets/4225039/150947ca-3981-4871-a5f0-104c019b7679">

**VS Code Extension Information (please complete the following information):**
 - OS: Windows
 - Version 5.0.0

**CLI Information (please complete the following information):**

**Comment by xzf0587** [comment]
Hi @ThomasPe,
Thank you for reaching out.
Since the TeamsFx 5 migration has backup all files under .backup folder, you can copy the missing "manifest.de-DE.json" to appPackage folder from "./backup/templates/appPackage" as a walk around. 
We logged it as a [known issue](https://github.com/OfficeDev/TeamsFx/wiki/Upgrade-project-to-use-Teams-Toolkit-5.0-features#files-missed-in-apppackage-folder)  in the wiki.
Thanks for your information.

**Comment by xzf0587** [comment]
Hi @ThomasPe 
It seems your problem has been solved based on your reaction. 
This issue will be closed for clean purpose.
Thanks for your information.
Please feel free to reopen it or open new issue if further problems.

**Comment by ThomasPe** [comment]
Well the workaround does work, still think the migration should not delete the files in the first place.

**Comment by xzf0587** [comment]
> Well the workaround does work, still think the migration should not delete the files in the first place.
@ThomasPe,
We will fix improve it in next release.
Thanks.

**Comment by xzf0587** [comment]
Hi @ThomasPe,
This bug has been fixed in https://github.com/OfficeDev/TeamsFx/pull/8934.
