### ISSUE TITLE
impossible to provision a new environment

### ISSUE THREAD

**Issue by christophemacabiau** [OfficeDev/TeamsFx#8922]
**Describe the bug**
impossible to provision a new environment

**To Reproduce**
create a new environment based on an old one (pre 5.0.0 toolkit version)
try to provision
I get the error:
_The ARM templates for deployment name: 'teams_toolkit_deployment' could not be deployed in resource group 'Vizygood2' for reason: ENOENT: no such file or directory, open '/home/christophe/code/vizygood/teams/templates/azure/azure.parameters.dev2.json'_

**Comment by blackchoey** [comment]
Hi @christophemacabiau thank you for reaching out to us. Sorry for the inconvenience caused by the missing parameter file error. To resolve this issue, you will need to manually create the missing file based on an existing parameter file and provide values for each of the parameters in the new file.

In Teams Toolkit 5.0, the environment management feature has evolved to give you more flexibility to customize your environment by referencing environment variables. However, there are some manual steps required when creating a new environment in Teams Toolkit 5.0, and creating the Azure parameter file is part of these steps. Please visit this link to learn more: https://github.com/OfficeDev/TeamsFx/wiki/Upgrade-project-to-use-Teams-Toolkit-5.0-features#environment-management.

If you don't want to manually create the parameter files when creating a new environment, you can create a new project using Teams Toolkit 5.0 and refer to the `teamsapp.yml` and `infra/azure.parameter.json` files to update your existing project's `teamsapp.yml` file to reference a single template Azure parameter file.

Please let us know if you need any further assistance.

**Comment by christophemacabiau** [comment]
Thank you for your answer @blackchoey 
In this json file we need the resourceBaseName which is as far as I understand determined by the provisioning? How do we fill this value?

**Comment by blackchoey** [comment]
@christophemacabiau you can give a preferred value in the json file. In Teams Toolkit 4.0, it will generate a random postfix after the app name as resourceBaseName when creating new environment (before provision).

**Comment by christophemacabiau** [comment]
Thanks @blackchoey!
