### ISSUE TITLE
When installing Azure Bot, App Service and App registration manually, notification not working

### ISSUE THREAD

**Issue by ajmal-yazdani** [OfficeDev/TeamsFx#9093]
**Describe the bug**
I have created a basic Notification Bot through "Microsoft Teams App" template and when trying to provision infra and deploy to Azure Cloud, all works, great tooling. 

**To Reproduce**
Now I want to do all the provisioning and deployment manually and one by one I am doing all steps, but in totality it's NOT working and I am getting forbidden or unauthorize error like,

POST /api/messages             401 Unauthorized

**Expected behavior**
How to make this work? Also can I deploy web App to Kubernetes cluster?

**Comment by ajmal-yazdani** [comment]
Managed Identity approach works for me.

**Comment by d-klotz** [comment]
Hello, I'm having the same issue: When provisioning a sample app using teamsFx CLI in azure, everything works fine, however, when using my local server to connect to the provisioned Azure Bot, it fails to connect. I have created new secrets in the app registration but it does not work, 401 Error is returned.

Here's a more detailed description: https://stackoverflow.com/questions/77129869/microsoft-bot-not-responding-although-the-server-is-hit-and-bot-is-provisioned

What is the fix for this?
