### ISSUE TITLE
Teams Toolkit Command Bot .net Error

### ISSUE THREAD

**Issue by RupKumar23** [OfficeDev/TeamsFx#9820]
**Describe the bug**
Microsoft.IdentityModel.Tokens.SecurityTokenNotYetValidException: IDX10222: Lifetime validation failed. The token is not yet valid. ValidFrom: '01-09-2023 06:06:44', Current time: '01-09-2023 05:58:11'.

**To Reproduce**
1. Create Command Bot project in Visaul Studio 2022 using Teams toolkit
2. Set Dev Tunnel 
3. Right click on project select Teams toolkit -> prepare teams app dependencies
4. Run F5 and Add bot in teams
5. write helloWorld in chat

**Expected behavior**
Bot should response back but getting error in command window

**Screenshots**
![image](https://github.com/OfficeDev/TeamsFx/assets/26250103/9458d799-4c5b-489a-ab9b-a00b8f5b71c5)

**VS Code Extension Information (please complete the following information):**

**CLI Information (please complete the following information):**

**Additional context**

**Comment by xiaolang124** [comment]
One possible solution to this issue is to check the time settings on your machine. If your machine’s time is not synchronized with an accurate time source, it can cause issues with token validation.

Another possible solution is to add the line 'Microsoft.IdentityModel.Logging.IdentityModelEventSource.ShowPII = true;' to your code. This will allow you to see more detailed information about the date and times in the error message, which can help you diagnose the issue.
